# Generated by Django 4.0.3 on 2022-05-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='substatus',
            field=models.BooleanField(default=False),
        ),
    ]
