# Generated by Django 4.0.3 on 2022-05-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_feedback_review'),
        ('account', '0002_profile_substatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.service'),
        ),
    ]
