# Generated by Django 4.0.3 on 2022-05-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_crs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='crs',
        ),
    ]
