# Generated by Django 4.0.3 on 2022-05-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_crs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_pro',
            field=models.ImageField(default='default\\default-user.png', upload_to='media'),
        ),
    ]
