# Generated by Django 4.0.3 on 2022-04-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ser', models.CharField(max_length=25)),
                ('desc_ser', models.TextField()),
                ('price_ser', models.IntegerField()),
                ('img_ser', models.ImageField(upload_to='media')),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
