# Generated by Django 4.0.3 on 2022-05-06 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_vediolecture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vediolecture',
            new_name='videolecture',
        ),
        migrations.RenameField(
            model_name='videolecture',
            old_name='desc_vediolecture',
            new_name='desc_videolecture',
        ),
    ]
