# Generated by Django 4.0.3 on 2022-05-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_vediolecture_videolecture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
