# Generated by Django 4.0.3 on 2022-05-09 07:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='review',
        ),
    ]
