# Generated by Django 4.0.3 on 2022-05-31 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Councelingdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=11)),
                ('topic', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
